---
baseurl: "/"
title: "Marco Janssen"
permalinks:
  post: /:year/:month/:slug
indexes:
  archive: "archive"
  category: "categories"
  tag: "tags"
params:
  image: "empire.png"
  description: "Software Engineer"
  keywords: "marco janssen, software engineer, php"